[project]
name = "officer-snorlax-bot"
version = "2.0.1"
description = "Officer Snorlax Discord bot created to open and close channels on a schedule."
authors = [{ name = "Adam Stewart" }]
requires-python = ">=3.13,<4"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "discord.py>=2.0.0,<3",
    "alembic>=1.8.1,<2",
    "sqlalchemy[asyncio]>=2.0,<3",
    "python-dotenv>=1,<2",
    "aiosqlite>=0,<1",
    "pytz>=2026.2",
    "pydantic-settings>=2.14.2",
]

[dependency-groups]
dev = [
    "ruff>=0,<1",
]

[tool.ruff]
line-length = 88
extend-exclude = ["alembic"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pydocstyle
    "D",
    # isort
    "I"
]

[tool.ruff.lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"

[tool.ruff.lint.isort]
lines-between-types = 1

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
