"""remove_join_filter

Revision ID: 1bf822cf359a
Revises: f8574e25d62d
Create Date: 2026-08-14 17:17:03.083353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf822cf359a'
down_revision = 'f8574e25d62d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'join_name_filter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('join_name_filter', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
